# Generated by Django 4.2.1 on 2023-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_episodios_ruta_imagen_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodios',
            name='ruta_episodio',
            field=models.CharField(default='no.jpg', max_length=50),
        ),
    ]
